# Generated by Django 4.2.13 on 2026-04-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_ledgerentry_payout_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_merchan_491d5c_idx",
            old_name="ledger_entries_merchant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="ledger_entr_merchan_2b8c6e_idx",
            old_name="ledger_entries_merchant_type_idx",
        ),
    ]
