# Generated by Django 4.2.13 on 2026-04-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="idempotency_merchan_16ab98_idx",
            old_name="idempotency_keys_merchant_key_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="idempotency_expires_6c9d28_idx",
            old_name="idempotency_keys_expires_at_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="payouts_merchan_44832a_idx",
            old_name="payouts_merchant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="payouts_status_726895_idx",
            old_name="payouts_status_started_at_idx",
        ),
    ]
